let productsDB = [
  {
    id: 1,
    title: 'nike',
    desc: 'Lorem, ipsum dolor sit amet consectetur',
    size: '40',
    price: '450EGP',
    imageUrl: 'img/shopping.webp',
    qty: 1,
    isMe: 'N',
  },
  {
    id: 2,
    title: 'adidas',
    desc: 'Lorem, ipsum dolor sit amet consectetur',
    size: '41',
    price: '450 EGP',
    imageUrl: 'img/shopping (1).webp',
    qty: 1,
    isMe: 'N',
  },
  {
    id: 3,
    title: 'converse',
    desc: 'Lorem, ipsum dolor sit amet consectetur',
    size: '42',
    price: '450EGP',
    imageUrl: 'img/shopping (2).webp',
    qty: 1,
    isMe: 'N',
  },
  {
    id: 4,
    title: 'lacoste',
    desc: 'Lorem, ipsum dolor sit amet consectetur',
    size: '43',
    price: '450EGP',
    imageUrl: 'img/shopping (3).webp',
    qty: 1,
    isMe: 'N',
  },
  {
    id: 5,
    title: 'pullandbear',
    desc: 'Lorem, ipsum dolor sit amet consectetur',
    size: '44',
    price: '450EGP',
    imageUrl: 'img/shopping (4).webp',
    qty: 1,
    isMe: 'N',
  },
  {
    id: 6,
    title: 'new balance',
    desc: 'Lorem, ipsum dolor sit amet consectetur',
    size: '45',
    price: '450EGP',
    imageUrl: 'img/shopping (5).webp',
    qty: 1,
    isMe: 'N',
  },
];
